apiVersion: v1
kind: LimitRange
metadata:
  name: workshop-defaults
  labels:
    app.kubernetes.io/part-of: ckad-namespace-workshop
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 256Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: workshop-quota
  labels:
    app.kubernetes.io/part-of: ckad-namespace-workshop
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.storage: 2Gi
    persistentvolumeclaims: "2"
    pods: "10"
