apiVersion: v1
kind: LimitRange
metadata:
  name: workshop-defaults
  labels:
    app.kubernetes.io/part-of: ckad-namespace-workshop
spec:
  limits:
    - type: Container
      # TODO: ajouter defaultRequest et default pour cpu/memory.
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: workshop-quota
  labels:
    app.kubernetes.io/part-of: ckad-namespace-workshop
spec:
  hard:
    # TODO: définir requests/limits, stockage, PVC et nombre de Pods.
    pods: "1"
